services:
  postgres:
    image: postgres:16-alpine3.22
    ports:
      - "5432:5432"
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:8.0.3-alpine
    restart: always
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "${PORT}:${PORT}"
      - "${PRISMA_STUDIO_PORT}:${PRISMA_STUDIO_PORT}"
    env_file:
      - .env
    volumes:
      - ./.env:/app/.env:ro
      - ./src:/app/src:ro
      - ./prisma:/app/prisma:rw
      - ./package.json:/app/package.json:ro
      - ./pnpm-lock.yaml:/app/pnpm-lock.yaml:ro

volumes:
  postgres_data:
  redis_data:
  node_modules:
